theme: jekyll-theme-minimal
title: Alec Reed
description: Research Assistant, Computer Science PhD Student, Unviersity of Colorado Boulder<br><br><a href="https://alre5639.github.io/Alec_CV_up.pdf" target="_blank">CV</a>
logo: IMG_0885.png
