theme: jekyll-theme-minimal
title: Alec Reed
description: Research Assistant, Computer Science PhD Student, Unviersity of Colorado Boulder<br><a href="https://alre5639.github.io/Alec_resume_dec.pdf" target="_blank">Resume.</a>
logo: IMG_0885.png
